import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {
  AiFillTwitterCircle, 
  AiFillLinkedin, 
  AiFillYoutube,
  AiFillGithub
}  from 'react-icons/ai';

import Image from 'next/image';
import deved from "../public/faaizuddin-transparent-image.png"

import {useState} from "react";

export default function Home() {

  const[darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? 'dark' : ""}>
      <Head>
        <title>Faaizuddin Farooqui Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className= 'min-h-screen'>

          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons dark:text-white'> FAAIZUDDIN FAROOQUI </h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill 
                onClick={() => setDarkMode(!darkMode)}
                className="cursor-pointer text-2xl dark:text-white" 
                />
              </li>
              <li> <a className = " bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8" href='./public/Faaizuddin_Farooqui_2023_Resume_4.pdf' target= "_blank"> Resume
              </a> </li>
            </ul>
          </nav>

          <div className='text-center p-10'>
            <h2 className="text-5xl text-teal-600 font-medium md:text-6xl"> 
              Faaizuddin Farooqui 
            </h2>
            <h3 className= "text-2xl py-2 md:text-3xl dark:text-white ">
              Developer and Student. 
            </h3>
            <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto'>  </p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
            <a href= "https://github.com/ffarooqui2" target = "_blank" className='dark:text-white'>
              <AiFillGithub />
            </a>
            <a href= "https://www.linkedin.com/in/faaizuddinf/" target = "_blank" className='dark:text-white'>
              <AiFillLinkedin />
            </a>
          </div>

          <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96'>
            <Image src={deved} layout='fill' objectFit='cover'/>

          </div>

        </section>

        <section>
          <div>
            <h3 className='text-3xl py-1 dark:text-teal-600 font-medium
            '> Current Status & Goals </h3>
            <p className ='text-md py-2 leading-8 text-gray-800 dark:text-white'>
                Ive taken a couple CS classes, blah blah blah. I am currently a <span className='text-teal-500'> sophomore </span>at my university but I plan on graduating early.
            </p>
            <p className ='text-md py-2 leading-8 text-gray-800 dark:text-white'>
                I aspire to become a <span className='text-teal-500'> software engineer</span>.
            </p>
          </div>
        </section>
      </main>
    </div>
  );
}
    